with open('tsv.txt', 'w')as file:
    file.write(platform.system()+'\n')
    file.write(platform.platform()+'\n')
    file.write(platform.version()+'\n')
    file.write(platform.machine()+'\n')
    file.write(platform.node()+'\n')
    file.write(platform.python_version()+'\n')
    file.write(platform.python_branch()+'\n')
    file.write(platform.release()+'\n')
    file.write(platform.processor()+'\n')
    file.write(platform.python_revision()+'\n')
    file.write(platform.python_build()[0]+'\n')
    file.write(platform.python_build()[1]+'\n')
    file.write(platform.python_compiler()+'\n')
    file.write(platform.uname().system+'\n')
    file.write(platform.uname().node+'\n')
    file.write(platform.uname().release+'\n')
    file.write(platform.uname().version+'\n')
    file.write(platform.uname().machine+'\n')
file = open('tsv.txt', 'r')
print(file.read())
